package models

// ShortURL contains hash of original URL.
//
// Generated by the service according to implemented hash function.
type ShortURL string

// OrigURL contains the full URL to be shortened.
//
// Must be a valid HTTP/HTTPS URL.
type OrigURL string

// URLPair is the core data transfer structure for the URL shortening service.
//
// It serves as the primary entity exchanged between service layers,
// containing both original and shortened URLs along with owner information.
// This structure is used throughout the application from storage layer
// to API responses.
type URLPair struct {
	UID   UserID   `json:"user_id"`
	Short ShortURL `json:"short_url"`
	Orig  OrigURL  `json:"original_url"`
}

// DelURLReq represents a request to delete a shortened URL.
//
// This structure is used to transfer deletion requests between service layers,
// containing both the shortened URL identifier and the user ID for ownership
// verification.
type DelURLReq struct {
	UID   UserID   `json:"user_id"`
	Short ShortURL `json:"short_url"`
}
