// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/handlers/ping.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockpingStorager is a mock of pingStorager interface.
type MockpingStorager struct {
	ctrl     *gomock.Controller
	recorder *MockpingStoragerMockRecorder
}

// MockpingStoragerMockRecorder is the mock recorder for MockpingStorager.
type MockpingStoragerMockRecorder struct {
	mock *MockpingStorager
}

// NewMockpingStorager creates a new mock instance.
func NewMockpingStorager(ctrl *gomock.Controller) *MockpingStorager {
	mock := &MockpingStorager{ctrl: ctrl}
	mock.recorder = &MockpingStoragerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpingStorager) EXPECT() *MockpingStoragerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockpingStorager) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockpingStoragerMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockpingStorager)(nil).Ping), arg0)
}
