// Code generated by MockGen. DO NOT EDIT.
// Source: batchdeleter.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rycln/shorturl/internal/models"
)

// MockBatchDeleterStorage is a mock of BatchDeleterStorage interface.
type MockBatchDeleterStorage struct {
	ctrl     *gomock.Controller
	recorder *MockBatchDeleterStorageMockRecorder
}

// MockBatchDeleterStorageMockRecorder is the mock recorder for MockBatchDeleterStorage.
type MockBatchDeleterStorageMockRecorder struct {
	mock *MockBatchDeleterStorage
}

// NewMockBatchDeleterStorage creates a new mock instance.
func NewMockBatchDeleterStorage(ctrl *gomock.Controller) *MockBatchDeleterStorage {
	mock := &MockBatchDeleterStorage{ctrl: ctrl}
	mock.recorder = &MockBatchDeleterStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchDeleterStorage) EXPECT() *MockBatchDeleterStorageMockRecorder {
	return m.recorder
}

// DeleteRequestedURLs mocks base method.
func (m *MockBatchDeleterStorage) DeleteRequestedURLs(arg0 context.Context, arg1 []*models.DelURLReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRequestedURLs", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRequestedURLs indicates an expected call of DeleteRequestedURLs.
func (mr *MockBatchDeleterStorageMockRecorder) DeleteRequestedURLs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRequestedURLs", reflect.TypeOf((*MockBatchDeleterStorage)(nil).DeleteRequestedURLs), arg0, arg1)
}
