// Code generated by MockGen. DO NOT EDIT.
// Source: ping.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPingStorage is a mock of PingStorage interface.
type MockPingStorage struct {
	ctrl     *gomock.Controller
	recorder *MockPingStorageMockRecorder
}

// MockPingStorageMockRecorder is the mock recorder for MockPingStorage.
type MockPingStorageMockRecorder struct {
	mock *MockPingStorage
}

// NewMockPingStorage creates a new mock instance.
func NewMockPingStorage(ctrl *gomock.Controller) *MockPingStorage {
	mock := &MockPingStorage{ctrl: ctrl}
	mock.recorder = &MockPingStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPingStorage) EXPECT() *MockPingStorageMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockPingStorage) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockPingStorageMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockPingStorage)(nil).Ping), arg0)
}
