// Code generated by MockGen. DO NOT EDIT.
// Source: stats.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rycln/shorturl/internal/models"
)

// MockStatsStorage is a mock of StatsStorage interface.
type MockStatsStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStatsStorageMockRecorder
}

// MockStatsStorageMockRecorder is the mock recorder for MockStatsStorage.
type MockStatsStorageMockRecorder struct {
	mock *MockStatsStorage
}

// NewMockStatsStorage creates a new mock instance.
func NewMockStatsStorage(ctrl *gomock.Controller) *MockStatsStorage {
	mock := &MockStatsStorage{ctrl: ctrl}
	mock.recorder = &MockStatsStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsStorage) EXPECT() *MockStatsStorageMockRecorder {
	return m.recorder
}

// GetStats mocks base method.
func (m *MockStatsStorage) GetStats(arg0 context.Context) (*models.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", arg0)
	ret0, _ := ret[0].(*models.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockStatsStorageMockRecorder) GetStats(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockStatsStorage)(nil).GetStats), arg0)
}
