// Code generated by MockGen. DO NOT EDIT.
// Source: deletionprocessor.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rycln/shorturl/internal/models"
)

// MockbatchDeleteServicer is a mock of batchDeleteServicer interface.
type MockbatchDeleteServicer struct {
	ctrl     *gomock.Controller
	recorder *MockbatchDeleteServicerMockRecorder
}

// MockbatchDeleteServicerMockRecorder is the mock recorder for MockbatchDeleteServicer.
type MockbatchDeleteServicerMockRecorder struct {
	mock *MockbatchDeleteServicer
}

// NewMockbatchDeleteServicer creates a new mock instance.
func NewMockbatchDeleteServicer(ctrl *gomock.Controller) *MockbatchDeleteServicer {
	mock := &MockbatchDeleteServicer{ctrl: ctrl}
	mock.recorder = &MockbatchDeleteServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbatchDeleteServicer) EXPECT() *MockbatchDeleteServicerMockRecorder {
	return m.recorder
}

// DeleteURLsBatch mocks base method.
func (m *MockbatchDeleteServicer) DeleteURLsBatch(arg0 context.Context, arg1 []*models.DelURLReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteURLsBatch", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteURLsBatch indicates an expected call of DeleteURLsBatch.
func (mr *MockbatchDeleteServicerMockRecorder) DeleteURLsBatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteURLsBatch", reflect.TypeOf((*MockbatchDeleteServicer)(nil).DeleteURLsBatch), arg0, arg1)
}
