// Code generated by MockGen. DO NOT EDIT.
// Source: stats.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rycln/shorturl/internal/models"
)

// MockstatsServicer is a mock of statsServicer interface.
type MockstatsServicer struct {
	ctrl     *gomock.Controller
	recorder *MockstatsServicerMockRecorder
}

// MockstatsServicerMockRecorder is the mock recorder for MockstatsServicer.
type MockstatsServicerMockRecorder struct {
	mock *MockstatsServicer
}

// NewMockstatsServicer creates a new mock instance.
func NewMockstatsServicer(ctrl *gomock.Controller) *MockstatsServicer {
	mock := &MockstatsServicer{ctrl: ctrl}
	mock.recorder = &MockstatsServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstatsServicer) EXPECT() *MockstatsServicerMockRecorder {
	return m.recorder
}

// GetStatsFromStorage mocks base method.
func (m *MockstatsServicer) GetStatsFromStorage(ctx context.Context) (*models.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatsFromStorage", ctx)
	ret0, _ := ret[0].(*models.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatsFromStorage indicates an expected call of GetStatsFromStorage.
func (mr *MockstatsServicerMockRecorder) GetStatsFromStorage(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatsFromStorage", reflect.TypeOf((*MockstatsServicer)(nil).GetStatsFromStorage), ctx)
}
